Hotel:
    type: entity
    table: hotel
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        prix:
            type: integer
            nullable: false
            options:
                unsigned: false
        img:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        desc:
            type: string
            nullable: false
            length: 500
            options:
                fixed: false
    lifecycleCallbacks: {  }
