# Doctrine.Tests.ORM.Mapping.User.dcm.yml
Doctrine\Tests\ORM\Mapping\User:
  type: entity
  repositoryClass: Doctrine\Tests\ORM\Mapping\UserRepository
  table: user
  schema: schema_name # The schema the table lies in, for platforms that support schemas (Optional, >= 2.5)
  readOnly: true
  indexes:
    name_index:
      columns: [ nom ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    prenom:
      type: string
      length: 50
    nom:
      type: string
      length: 50
    adresse:
      type: string
      length: 100
    cp:
      type: int
      length: 10
    ville:
      type: string
      length: 50
    tel:
      type: int
      length: 50
    email:
      type: string
      length: 32
      column: user_email
      unique: true
      options:
        fixed: true
        comment: User's email address
    civ:
      type: bool
      length: 50
    login:
      type: string
      length: 50
    password:
      type: string
      length: 50
    pays:
      type: string
      length: 50
    