User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        prenom:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        nom:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        adresse:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        cp:
            type: integer
            nullable: true
            options:
                unsigned: false
        ville:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        tel:
            type: string
            nullable: false
            length: 12
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        civ:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
        login:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        pays:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
